### ISSUE TITLE
How can I update all existing documents to have a slug?

### ISSUE THREAD

**Issue by ZeldOcarina** [YuriGor/mongoose-slug-updater#15]
Hello!
I've created a web app without thinking since the beginning with slugs and now it's a mess.
I have about 150 documents in there.
How could I programmatically add a slug with this plugin?
I would have to change the slugified value for each one but each one has a different one.
Is there any solution? Cannot find anything in the docs!
Thanks a lot!

**Comment by YuriGor** [comment]
Hi, it's a one time action right, so no need to worry about performance?
Well, maybe write a script to query them all, iterate over the list, update source field of each record by appending some symbol, save the record, remove that trailing symbol and save again?

**Comment by YuriGor** [comment]
And if you have counter in your slug - make sure to query them in desired order.

**Comment by ZeldOcarina** [comment]
Ok so something like this?

const Immobile = require('./models/immobile');

(async function() {
	const documents = await Model.find();
	documents.forEach(async (document) => {
		await Model.updateOne({ _id: document._id }, { $set: { <field>: document.<field> + '-' } });
		await Model.updateOne({ _id: document._id }, { $set: { <field>: document.<field> } });
		console.log('document saved');
	});
	console.log('updated');
})();

"And if you have counter in your slug - make sure to query them in desired order."

I have a counter but I did not quite get this sentence, how would I do this?

Thanks a lot for this marvelous mongoose plugin!

**Comment by YuriGor** [comment]
Yes, this should work.
About counter I mean you maybe will want to regenerate slugs in chronological order, so duplicate slugs for records created later will have bigger counter.
In case of your records were created in db in some other than chronological order. (e.g. was imported or whatever)

**Comment by ZeldOcarina** [comment]
Ok great!! I will try this tonight as it's a production DB!
Thanks a lot for your precious help! 🥇

**Comment by YuriGor** [comment]
Also thank you for feedback, consider to put a star four GitHub project, so awesomeness of it will be officially accountable :)

**Comment by YuriGor** [comment]
If it's in production, I'd prefer to clone a collection and test it first.

**Comment by ZeldOcarina** [comment]
Starred! I've tried to clone the collection the WHOLE day but it keeps giving me duplication errors on the slug and/or id fields...
I've tested with some documents on the test DB and it seems to be working..

**Comment by YuriGor** [comment]
Cool, now you are at Superstar Support Plan, so let me know how it will go. I expect no data corruption.

About duplication errors - did you clone by manually inserting docs from one collection to another? With plugin enabled? If there are some errors caused by plugin please report a bug.

Only thing I can expect if you inserted\updated records asynchronously without awaiting reach operation. Counters are not recommended for high load, because there is no good way in mongo to keep consistent counters in case of two equal values appeared in collection "simultaneously". While plugin checks if such slug already exists, it's possible to have changes in the data. 

But I believe there should be a possibility to just clone collection in, you know, administrative way, "cloneCollection" afair, in this case plugin will not be triggered.

**Comment by ZeldOcarina** [comment]
I've tried with a node script, by command line and through a json backup. I'll let you know how it goes. Thanks a lot for your superstar support! I love all open source projects guys and I think this plugin can definitely become the best slug package in npm! :)

**Comment by YuriGor** [comment]
I will print this comment and pin to the wall, thank you :)

**Comment by YuriGor** [comment]
I hope it was fine, will close for now.

**Comment by adventurini** [comment]
This does not work. It creates duplicates.
