### ISSUE TITLE
Unique slug counter refers to last created item

### ISSUE THREAD

**Issue by OBats** [YuriGor/mongoose-slug-updater#8]
Hi!

First of all - thank you so much for your desire to maintain this plugin. Your efforts worth it ;)

Notice one interesting detail: I generate my slug from item title and has `unique: true` & `slugPaddingSize: 2` properties in my schema. When the title is repeated it takes further counter (e.g. `item-01`).

For example, I have 10 items with the same title, so it last slug will be `item-09`. If I delete some of the previous items, for example, `item-01` till `item-08` new created item with the same title as previous will be `item-10`, not `item-01`.

Is it correct behavior? Should slug just referred to the last created item and increase the counter, or it should "fills" place of deleted one (`item-01` in my case)?

Thank you for your assistance!)

**Comment by YuriGor** [comment]
Hi @OBats, yes this is expected behavior.
The most common usage of slugs is generating permalinks.
 If permalink was shared somewhere and corresponding page was deleted, it's less confusing to show 404 error page, then to show some irrelevant content.
So I'd say reusing of last deleted counter will be not so correct, but memorising it somehow to prevent reusing after deletion will cost too much to care about.

If you need "filling the holes" feature could you please describe your use case?
Note, that such option, if it will be implemented, will cost some performance, because plugin will need to load not only most recent counter, but all of them, to iterate over and find the "hole".

**Comment by OBats** [comment]
@YuriGor seems you are right. Show 404 error page is better than show irrelevant content.

And yes, I realized performance costs and seems it doesn't worth it.

Thank you! :)

**Comment by YuriGor** [comment]
Depends on write rate. 

If creation\renaming docs is rare, performance impact will be low.
But looks like you are agree that 404 is better in your case too.

If rate is very high - it's better to not use counter at all, and use random postfix, preferably with 'force' flag, because there is a chance to have duplicate conflict, if the same slug will be counted at the same time two or more times (for example if two authors will submit article with identical title synchronously)

So feel free to describe your use case in details, and we will see what the option will fit your case your better.
